title: Bitcoin Anyprevout and Eltoo tests
author: Richard Myers
email: remyers@yakshaver.org
description: > # this means to ignore newlines until "baseurl:"
  This site is dedicated to efforts to further the specification, implementation and testing of two related projects: BIP-118 and the eltoo Lightning protocol.

# social links
twitter_username: remyers_
github_username:  remyers

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
